version: '3.6'

services:
  api:
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    image: quay.io/go-skynet/local-ai:v1.40.0-cublas-cuda12
    tty: true # enable colorized logs
    restart: always # should this be on-failure ?
    privileged: true
    ports:
      - 9095:8080
    env_file:
      - .env
    volumes:
      - ./models:/models
    command: ["/usr/bin/local-ai" ]
